package com.OpenStreetMap.View;

import com.OpenStreetMap.Controller.ControllerRoutes;
import com.OpenStreetMap.Controller.ControllerStudenti;
import com.OpenStreetMap.Controller.Database;
import com.OpenStreetMap.Controller.Dijkstra;
import com.OpenStreetMap.Controller.ExportMap;
import com.OpenStreetMap.Controller.ImportMap;
import com.OpenStreetMap.Controller.ImportPlotMap;
import com.OpenStreetMap.Controller.Visit;
import com.OpenStreetMap.Model.Arc;
import com.OpenStreetMap.Model.Node;
import com.OpenStreetMap.Model.Route;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

public class GUI extends javax.swing.JFrame {

    ImportMap importMap = new ImportMap();
    ExportMap exportMap = new ExportMap();
    Database database = new Database();
    ImportPlotMap importPlotMap = new ImportPlotMap();
    ControllerRoutes controllerRoutes = new ControllerRoutes();
    ControllerStudenti controllerStudenti = new ControllerStudenti();
    Visit visit = new Visit();
    Dijkstra dijkstra = new Dijkstra();

    private DB dbStreetMap = null;
    private HashMap<Long, Node> nodes = null;
    private HashSet<Arc> arcs = null;
    private HashMap<Long, Node> nodes_paint = null;
    private HashSet<Arc> arcs_paint = null;
    private HashSet<Route> routes = null;
    private HashSet<Node> nodes_students = null;

    private File file = null;

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        mappa_jPanel = new JPanel(){

            @Override
            public void paint(Graphics g) {
                super.paint(g);
                disegna(g);
            }

        };
        tratte_jPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tratteOutput_jTextArea = new javax.swing.JTextArea();
        tratte_jButton = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        tratteInput_jTextArea = new javax.swing.JTextArea();
        utenti_jPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        utentiInput_jTextArea = new javax.swing.JTextArea();
        utenti_jButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        utentiOutput_jTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        allStopRoute_jTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        idealStopRoute_jTextArea = new javax.swing.JTextArea();
        allRoute_jButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        allStopIdealRoute_jTextArea = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        idealStopIdealRoute_jTextArea = new javax.swing.JTextArea();
        idealRoute_jButton = new javax.swing.JButton();
        altro_jPanel = new javax.swing.JPanel();
        sLat_jTextField = new javax.swing.JTextField();
        sLon_jTextField = new javax.swing.JTextField();
        dLat_jTextField = new javax.swing.JTextField();
        dLon_jTextField = new javax.swing.JTextField();
        randomDijkstra_jButton = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        dijkstraOutput_jTextArea = new javax.swing.JTextArea();
        dijkstra_jButton = new javax.swing.JButton();
        lat_jTextField = new javax.swing.JTextField();
        lon_jTextField = new javax.swing.JTextField();
        randomVisita_jButton = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        visitaOutput_jTextArea = new javax.swing.JTextArea();
        visita_jButton = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        mappa_jMenu = new javax.swing.JMenu();
        caricaEsporta_jMenuItem = new javax.swing.JMenuItem();
        disegna_jMenuItem = new javax.swing.JMenuItem();
        reset_jMenuItem = new javax.swing.JMenuItem();
        cancella_jMenuItem = new javax.swing.JMenuItem();
        esci_jMenuItem = new javax.swing.JMenuItem();
        database_jMenu = new javax.swing.JMenu();
        connettiDB_jMenuItem = new javax.swing.JMenuItem();
        inserisciDB_jMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mappa_jPanel.setBackground(new java.awt.Color(255, 255, 255));
        mappa_jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mappa_jPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mappa_jPanelLayout = new javax.swing.GroupLayout(mappa_jPanel);
        mappa_jPanel.setLayout(mappa_jPanelLayout);
        mappa_jPanelLayout.setHorizontalGroup(
            mappa_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1456, Short.MAX_VALUE)
        );
        mappa_jPanelLayout.setVerticalGroup(
            mappa_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Mappa", mappa_jPanel);

        tratteOutput_jTextArea.setColumns(20);
        tratteOutput_jTextArea.setRows(5);
        jScrollPane1.setViewportView(tratteOutput_jTextArea);

        tratte_jButton.setText("Crea");
        tratte_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratte_jButtonActionPerformed(evt);
            }
        });

        tratteInput_jTextArea.setColumns(20);
        tratteInput_jTextArea.setRows(5);
        jScrollPane11.setViewportView(tratteInput_jTextArea);

        javax.swing.GroupLayout tratte_jPanelLayout = new javax.swing.GroupLayout(tratte_jPanel);
        tratte_jPanel.setLayout(tratte_jPanelLayout);
        tratte_jPanelLayout.setHorizontalGroup(
            tratte_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tratte_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tratte_jButton)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        tratte_jPanelLayout.setVerticalGroup(
            tratte_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tratte_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tratte_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane11))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tratte_jPanelLayout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addComponent(tratte_jButton)
                .addGap(324, 324, 324))
        );

        jTabbedPane.addTab("Tratte", tratte_jPanel);

        utentiInput_jTextArea.setColumns(20);
        utentiInput_jTextArea.setRows(5);
        jScrollPane4.setViewportView(utentiInput_jTextArea);

        utenti_jButton.setText("Crea");
        utenti_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utenti_jButtonActionPerformed(evt);
            }
        });

        utentiOutput_jTextArea.setColumns(20);
        utentiOutput_jTextArea.setRows(5);
        jScrollPane5.setViewportView(utentiOutput_jTextArea);

        allStopRoute_jTextArea.setColumns(20);
        allStopRoute_jTextArea.setRows(5);
        jScrollPane3.setViewportView(allStopRoute_jTextArea);

        idealStopRoute_jTextArea.setColumns(20);
        idealStopRoute_jTextArea.setRows(5);
        jScrollPane6.setViewportView(idealStopRoute_jTextArea);

        allRoute_jButton.setText("All");
        allRoute_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRoute_jButtonActionPerformed(evt);
            }
        });

        allStopIdealRoute_jTextArea.setColumns(20);
        allStopIdealRoute_jTextArea.setRows(5);
        jScrollPane7.setViewportView(allStopIdealRoute_jTextArea);

        idealStopIdealRoute_jTextArea.setColumns(20);
        idealStopIdealRoute_jTextArea.setRows(5);
        jScrollPane8.setViewportView(idealStopIdealRoute_jTextArea);

        idealRoute_jButton.setText("Ideal");
        idealRoute_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idealRoute_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout utenti_jPanelLayout = new javax.swing.GroupLayout(utenti_jPanel);
        utenti_jPanel.setLayout(utenti_jPanelLayout);
        utenti_jPanelLayout.setHorizontalGroup(
            utenti_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utenti_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(utenti_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(utenti_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(utenti_jPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utenti_jPanelLayout.createSequentialGroup()
                        .addComponent(utenti_jButton)
                        .addGap(149, 149, 149)))
                .addGroup(utenti_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(utenti_jPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
            .addGroup(utenti_jPanelLayout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(allRoute_jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idealRoute_jButton)
                .addGap(410, 410, 410))
        );
        utenti_jPanelLayout.setVerticalGroup(
            utenti_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utenti_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(utenti_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(utenti_jPanelLayout.createSequentialGroup()
                        .addGroup(utenti_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utenti_jPanelLayout.createSequentialGroup()
                        .addComponent(utenti_jButton)
                        .addGap(74, 74, 74)))
                .addGroup(utenti_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(utenti_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allRoute_jButton)
                    .addComponent(idealRoute_jButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Utenti", utenti_jPanel);

        sLon_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sLon_jTextFieldActionPerformed(evt);
            }
        });

        dLat_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dLat_jTextFieldActionPerformed(evt);
            }
        });

        dLon_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dLon_jTextFieldActionPerformed(evt);
            }
        });

        randomDijkstra_jButton.setText("Random");
        randomDijkstra_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomDijkstra_jButtonActionPerformed(evt);
            }
        });

        dijkstraOutput_jTextArea.setColumns(20);
        dijkstraOutput_jTextArea.setRows(5);
        jScrollPane9.setViewportView(dijkstraOutput_jTextArea);

        dijkstra_jButton.setText("Dijkstra");
        dijkstra_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dijkstra_jButtonActionPerformed(evt);
            }
        });

        randomVisita_jButton.setText("Random");
        randomVisita_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomVisita_jButtonActionPerformed(evt);
            }
        });

        visitaOutput_jTextArea.setColumns(20);
        visitaOutput_jTextArea.setRows(5);
        jScrollPane10.setViewportView(visitaOutput_jTextArea);

        visita_jButton.setText("Visita");
        visita_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visita_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout altro_jPanelLayout = new javax.swing.GroupLayout(altro_jPanel);
        altro_jPanel.setLayout(altro_jPanelLayout);
        altro_jPanelLayout.setHorizontalGroup(
            altro_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altro_jPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(altro_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(altro_jPanelLayout.createSequentialGroup()
                        .addGroup(altro_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lon_jTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(lat_jTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(randomVisita_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(dLon_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(altro_jPanelLayout.createSequentialGroup()
                        .addComponent(dLat_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(randomDijkstra_jButton))
                    .addComponent(sLon_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLat_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(altro_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jScrollPane10))
                .addGap(67, 67, 67)
                .addGroup(altro_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dijkstra_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visita_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(478, Short.MAX_VALUE))
        );
        altro_jPanelLayout.setVerticalGroup(
            altro_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altro_jPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(altro_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9)
                    .addGroup(altro_jPanelLayout.createSequentialGroup()
                        .addComponent(sLat_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sLon_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(altro_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(altro_jPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(dLat_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(altro_jPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(randomDijkstra_jButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dLon_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(altro_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(altro_jPanelLayout.createSequentialGroup()
                        .addGroup(altro_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(altro_jPanelLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(lat_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lon_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(altro_jPanelLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(randomVisita_jButton)))
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altro_jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))))
            .addGroup(altro_jPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(dijkstra_jButton)
                .addGap(205, 205, 205)
                .addComponent(visita_jButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Altro", altro_jPanel);

        mappa_jMenu.setText("Mappa");

        caricaEsporta_jMenuItem.setText("Carica/Esporta");
        caricaEsporta_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caricaEsporta_jMenuItemActionPerformed(evt);
            }
        });
        mappa_jMenu.add(caricaEsporta_jMenuItem);

        disegna_jMenuItem.setText("Disegna");
        disegna_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disegna_jMenuItemActionPerformed(evt);
            }
        });
        mappa_jMenu.add(disegna_jMenuItem);

        reset_jMenuItem.setText("Reset");
        reset_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_jMenuItemActionPerformed(evt);
            }
        });
        mappa_jMenu.add(reset_jMenuItem);

        cancella_jMenuItem.setText("Cancella");
        cancella_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancella_jMenuItemActionPerformed(evt);
            }
        });
        mappa_jMenu.add(cancella_jMenuItem);

        esci_jMenuItem.setText("Esci");
        esci_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esci_jMenuItemActionPerformed(evt);
            }
        });
        mappa_jMenu.add(esci_jMenuItem);

        jMenuBar.add(mappa_jMenu);

        database_jMenu.setText("Database");

        connettiDB_jMenuItem.setText("Connetti");
        connettiDB_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connettiDB_jMenuItemActionPerformed(evt);
            }
        });
        database_jMenu.add(connettiDB_jMenuItem);

        inserisciDB_jMenuItem.setText("Inserisci");
        inserisciDB_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserisciDB_jMenuItemActionPerformed(evt);
            }
        });
        database_jMenu.add(inserisciDB_jMenuItem);

        jMenuBar.add(database_jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disegna_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disegna_jMenuItemActionPerformed
        file = openFile();
        if (disegnaMap(file)) {
            reset_jMenuItem.setEnabled(true);
            cancella_jMenuItem.setEnabled(true);
            jTabbedPane.setEnabled(true);

            mappa_jPanel.repaint();
        }
    }//GEN-LAST:event_disegna_jMenuItemActionPerformed

    private void caricaEsporta_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caricaEsporta_jMenuItemActionPerformed
        file = openFile();

        if (file != null) {
            importMap.create(file, 5, 2, 100, false, false);
            nodes = importMap.getNodes();
            arcs = importMap.getArcs();

            if (!nodes.isEmpty() || !arcs.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Mappa creata nodi: " + nodes.size() + " archi: " + arcs.size());

                connettiDB_jMenuItem.setEnabled(true);

                file = selectPath();
                if (esportaMap(file)) {
                    Object[] options = {"Si", "No"};
                    int option = JOptionPane.showOptionDialog(null, "Mappa esportata, disegnare mappa?", null, JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);

                    if (option == 0) {
                        if (disegnaMap(file)) {
                            reset_jMenuItem.setEnabled(true);
                            cancella_jMenuItem.setEnabled(true);
                            jTabbedPane.setEnabled(true);

                            mappa_jPanel.repaint();
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Mappa non esportata");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Mappa non creata");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mappa non caricata");
        }
    }//GEN-LAST:event_caricaEsporta_jMenuItemActionPerformed

    private void esci_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esci_jMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_esci_jMenuItemActionPerformed

    private void connettiDB_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connettiDB_jMenuItemActionPerformed
        dbStreetMap = database.connectDB("localhost", 27017, "StreetMap");
        if (dbStreetMap != null) {
            JOptionPane.showMessageDialog(null, "Connesso al DB");
            inserisciDB_jMenuItem.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Connessione al DB non riuscita");
        }
    }//GEN-LAST:event_connettiDB_jMenuItemActionPerformed

    private void inserisciDB_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserisciDB_jMenuItemActionPerformed
        DBCollection collectionNode = database.getCollection(dbStreetMap, "Node");
        DBCollection collectionWay = database.getCollection(dbStreetMap, "Way");
        DBCollection collectionArc = database.getCollection(dbStreetMap, "Arc");

        database.insertNodesDB(collectionNode, importMap.getNodes());
        database.insertWaysDB(collectionWay, importMap.getWays());
        database.insertArcsDB(collectionArc, importMap.getArcs());

        JOptionPane.showMessageDialog(null, "Elementi inseriti");
    }//GEN-LAST:event_inserisciDB_jMenuItemActionPerformed

    private void sLon_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sLon_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sLon_jTextFieldActionPerformed

    private void dLon_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dLon_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dLon_jTextFieldActionPerformed

    private void dLat_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dLat_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dLat_jTextFieldActionPerformed

    private void mappa_jPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mappa_jPanelMouseClicked
        int x = evt.getX();
        int y = evt.getY();

        Node n = getNodoVicinoByXY(x, y);
        System.out.println("index: " + n.getIndex() + "; id: " + n.getId() + "; " + n.getLat() + "," + n.getLon());

        JPanel panelMouseListener = new JPanel();
        if (n.getNum_studenti() <= 0) {
            JLabel node_label = new JLabel("index: " + n.getIndex() + "; id: " + n.getId() + " lat: " + n.getLat() + " lon: " + n.getLon());
            panelMouseListener.add(node_label);
        } else {
            JLabel node_label = new JLabel("index: " + n.getIndex() + "; id: " + n.getId() + " lat: " + n.getLat() + " lon: " + n.getLon() + " num: " + n.getNum_studenti());
            panelMouseListener.add(node_label);
        }

        final int TRATTE = 0;
        final int UTENTI = 1;
        final int DIJKSTRA = 2;
        final int VISITA = 3;
        final int ANNULLA = 4;

        Object[] options = {"Tratte", "Utenti", "Dijkstra", "Visita", "Annulla"};
        int option = JOptionPane.showOptionDialog(null, panelMouseListener, "Nodo selezionato", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);

        switch (option) {
            case TRATTE:
                tratteInput_jTextArea.append("# " + n.getLat() + " " + n.getLon() + "\n");
                break;
            case UTENTI:
                utentiInput_jTextArea.append("# " + n.getLat() + " " + n.getLon() + "\n");
                break;
            case DIJKSTRA:
                Object[] options2 = {"Sorgente", "Destinazione", "Annulla"};
                int option2 = JOptionPane.showOptionDialog(null, null, "Dijkstra", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options2, options2[0]);

                if (option2 == 0) {
                    sLat_jTextField.setText(String.valueOf(n.getLat()));
                    sLon_jTextField.setText(String.valueOf(n.getLon()));
                }
                if (option2 == 1) {
                    dLat_jTextField.setText(String.valueOf(n.getLat()));
                    dLon_jTextField.setText(String.valueOf(n.getLon()));
                }
                if (option2 == 2) {
                    break;
                }
                break;
            case VISITA:
                lat_jTextField.setText(String.valueOf(n.getLat()));
                lon_jTextField.setText(String.valueOf(n.getLon()));
                break;
            case ANNULLA:
                break;
        }
    }//GEN-LAST:event_mappa_jPanelMouseClicked

    private void reset_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_jMenuItemActionPerformed
        resetComponent();
        resetMark();
        resetStudent();
        routes = null;
        nodes_students = null;

        mappa_jPanel.repaint();
    }//GEN-LAST:event_reset_jMenuItemActionPerformed

    private void cancella_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancella_jMenuItemActionPerformed
        resetComponent();
        resetMark();
        cancel();

        mappa_jPanel.repaint();
    }//GEN-LAST:event_cancella_jMenuItemActionPerformed

    private void tratte_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratte_jButtonActionPerformed
        String area = tratteInput_jTextArea.getText();

        routes = controllerRoutes.read(area, nodes);

        String output_routes = controllerRoutes.printRoutes(routes);
        tratteOutput_jTextArea.setText(output_routes);

        mappa_jPanel.repaint();
    }//GEN-LAST:event_tratte_jButtonActionPerformed

    private void randomDijkstra_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomDijkstra_jButtonActionPerformed
        Node sorgente = Node.randomNode(nodes);
        Node destinazione = Node.randomNode(nodes);

        sLat_jTextField.setText(String.valueOf(sorgente.getLat()));
        sLon_jTextField.setText(String.valueOf(sorgente.getLon()));
        dLat_jTextField.setText(String.valueOf(destinazione.getLat()));
        dLon_jTextField.setText(String.valueOf(destinazione.getLon()));
    }//GEN-LAST:event_randomDijkstra_jButtonActionPerformed

    private void randomVisita_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomVisita_jButtonActionPerformed
        Node startingNode = Node.randomNode(nodes);

        lat_jTextField.setText(String.valueOf(startingNode.getLat()));
        lon_jTextField.setText(String.valueOf(startingNode.getLon()));
    }//GEN-LAST:event_randomVisita_jButtonActionPerformed

    private void dijkstra_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dijkstra_jButtonActionPerformed
        float lat_s = Float.parseFloat(sLat_jTextField.getText());
        float lon_s = Float.parseFloat(sLon_jTextField.getText());
        float lat_d = Float.parseFloat(dLat_jTextField.getText());
        float lon_d = Float.parseFloat(dLon_jTextField.getText());

        Node sorgente = Node.nodeByLatLon(nodes, lat_s, lon_s);
        Node destinazione = Node.nodeByLatLon(nodes, lat_d, lon_d);

        ArrayList<Node> percorso = dijkstra.run(sorgente, destinazione, nodes, true);

        String output_dijkstra = dijkstra.printPercorso(percorso);
        dijkstraOutput_jTextArea.setText(output_dijkstra);

        mappa_jPanel.repaint();
    }//GEN-LAST:event_dijkstra_jButtonActionPerformed

    private void visita_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visita_jButtonActionPerformed
        float lat = Float.parseFloat(lat_jTextField.getText());
        float lon = Float.parseFloat(lon_jTextField.getText());

        Node startingNode = Node.nodeByLatLon(nodes, lat, lon);

        ArrayList<Node> visit_nodes = visit.visita(nodes, startingNode);

        String output_visit = visit.printVisit(visit_nodes);
        visitaOutput_jTextArea.setText(output_visit);

        mappa_jPanel.repaint();
    }//GEN-LAST:event_visita_jButtonActionPerformed

    private void idealRoute_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idealRoute_jButtonActionPerformed
        HashMap<Node, HashMap<ArrayList<Node>, Double>> allRoute = controllerStudenti.allRoute(nodes, nodes_students, routes);
        String output_fermate = controllerStudenti.printPercorsi(allRoute);
        allStopIdealRoute_jTextArea.setText(output_fermate);

        HashMap<Node, HashMap<ArrayList<Node>, Double>> idealStop = controllerStudenti.idealStop(allRoute);
        String output_fermateIdeal = controllerStudenti.printPercorsi(idealStop);
        idealStopIdealRoute_jTextArea.setText(output_fermateIdeal);
    }//GEN-LAST:event_idealRoute_jButtonActionPerformed

    private void allRoute_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRoute_jButtonActionPerformed
        HashMap<Node, HashMap<ArrayList<Node>, Double>> allStop = controllerStudenti.allStop(nodes, nodes_students, routes);
        String output_fermate = controllerStudenti.printPercorsi(allStop);
        allStopRoute_jTextArea.setText(output_fermate);

        HashMap<Node, HashMap<ArrayList<Node>, Double>> idealStop = controllerStudenti.idealStop(allStop);
        String output_fermateIdeal = controllerStudenti.printPercorsi(idealStop);
        idealStopRoute_jTextArea.setText(output_fermateIdeal);
    }//GEN-LAST:event_allRoute_jButtonActionPerformed

    private void utenti_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utenti_jButtonActionPerformed
        String area = utentiInput_jTextArea.getText().toString();

        nodes_students = controllerStudenti.read(area, nodes, routes);
        String output_nodes_students = "";
        for (Iterator<Node> it = nodes_students.iterator(); it.hasNext();) {
            Node node = it.next();

            output_nodes_students += "id: " + node.getId() + " index: " + node.getIndex() + " lat: " + node.getLat() + " lon: " + node.getLon() + " tratta: " + node.getRoute().getName() + " num: " + node.getNum_studenti() + "\n";

        }
        utentiOutput_jTextArea.setText(output_nodes_students);

        mappa_jPanel.repaint();
    }//GEN-LAST:event_utenti_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allRoute_jButton;
    private javax.swing.JTextArea allStopIdealRoute_jTextArea;
    private javax.swing.JTextArea allStopRoute_jTextArea;
    private javax.swing.JPanel altro_jPanel;
    private javax.swing.JMenuItem cancella_jMenuItem;
    private javax.swing.JMenuItem caricaEsporta_jMenuItem;
    private javax.swing.JMenuItem connettiDB_jMenuItem;
    private javax.swing.JTextField dLat_jTextField;
    private javax.swing.JTextField dLon_jTextField;
    private javax.swing.JMenu database_jMenu;
    private javax.swing.JTextArea dijkstraOutput_jTextArea;
    private javax.swing.JButton dijkstra_jButton;
    private javax.swing.JMenuItem disegna_jMenuItem;
    private javax.swing.JMenuItem esci_jMenuItem;
    private javax.swing.JButton idealRoute_jButton;
    private javax.swing.JTextArea idealStopIdealRoute_jTextArea;
    private javax.swing.JTextArea idealStopRoute_jTextArea;
    private javax.swing.JMenuItem inserisciDB_jMenuItem;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField lat_jTextField;
    private javax.swing.JTextField lon_jTextField;
    private javax.swing.JMenu mappa_jMenu;
    private javax.swing.JPanel mappa_jPanel;
    private javax.swing.JButton randomDijkstra_jButton;
    private javax.swing.JButton randomVisita_jButton;
    private javax.swing.JMenuItem reset_jMenuItem;
    private javax.swing.JTextField sLat_jTextField;
    private javax.swing.JTextField sLon_jTextField;
    private javax.swing.JTextArea tratteInput_jTextArea;
    private javax.swing.JTextArea tratteOutput_jTextArea;
    private javax.swing.JButton tratte_jButton;
    private javax.swing.JPanel tratte_jPanel;
    private javax.swing.JTextArea utentiInput_jTextArea;
    private javax.swing.JTextArea utentiOutput_jTextArea;
    private javax.swing.JButton utenti_jButton;
    private javax.swing.JPanel utenti_jPanel;
    private javax.swing.JTextArea visitaOutput_jTextArea;
    private javax.swing.JButton visita_jButton;
    // End of variables declaration//GEN-END:variables

    private File openFile() {
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("Scegli file streetMap");

        if (jFileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            String pathFile = jFileChooser.getSelectedFile().getPath();

            File file = new File(pathFile);

            System.out.println("SCELTA FILE");
            System.out.println("   Aperto file: " + pathFile);

            return file;
        } else {
            System.out.println("Nessun file selezionato");
            return null;
        }
    }

    private File selectPath() {
        FileNameExtensionFilter grfFilter = new FileNameExtensionFilter("osm.grf files (*osm.grf)", "osm.grf");
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("Scegli cartella destinazione");
        jFileChooser.addChoosableFileFilter(grfFilter);
        jFileChooser.setFileFilter(grfFilter);

        File file = null;

        if (jFileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            file = jFileChooser.getSelectedFile();

            return file;
        } else {
            System.out.println("Nessun percorso selezionato");
            return null;
        }

    }

    private void resetComponent() {

        tratteInput_jTextArea.setText("");
        tratteOutput_jTextArea.setText("");
        utentiInput_jTextArea.setText("");
        utentiOutput_jTextArea.setText("");
        allStopRoute_jTextArea.setText("");
        idealStopRoute_jTextArea.setText("");
        allStopIdealRoute_jTextArea.setText("");
        idealStopIdealRoute_jTextArea.setText("");
        sLat_jTextField.setText("");
        sLon_jTextField.setText("");
        dLat_jTextField.setText("");
        dLon_jTextField.setText("");
        dijkstraOutput_jTextArea.setText("");
        lat_jTextField.setText("");
        lon_jTextField.setText("");
        visitaOutput_jTextArea.setText("");
    }

    private void resetMark() {
        for (Iterator<Node> it = nodes.values().iterator(); it.hasNext();) {
            Node node = it.next();
            node.setMark(-1);

            for (Iterator<Arc> it1 = node.nd_arcs.iterator(); it1.hasNext();) {
                Arc arc = it1.next();
                arc.setMark(0);
            }
        }
    }

    private void resetStudent() {
        for (Iterator<Node> it = nodes.values().iterator(); it.hasNext();) {
            Node node = it.next();
            node.setNum_studenti(0);
        }
    }

    private void cancel() {
        nodes = null;
        arcs = null;
        nodes_paint = null;
        arcs_paint = null;
        routes = null;
        nodes_students = null;

        reset_jMenuItem.setEnabled(false);
        cancella_jMenuItem.setEnabled(false);
        jTabbedPane.setEnabled(false);
    }

    private Node getNodoVicinoByXY(int x, int y) {

        Node ndOut = null;

        int minX = Integer.MAX_VALUE;
        int maxX = Integer.MIN_VALUE;
        int minY = Integer.MAX_VALUE;
        int maxY = Integer.MIN_VALUE;

        if (nodes_paint != null && arcs_paint != null) {
            for (Node n : nodes_paint.values()) {
                if (n.getX() > maxX) {
                    maxX = n.getX();
                }
                if (n.getX() < minX) {
                    minX = n.getX();
                }
                if (n.getY() > maxY) {
                    maxY = n.getY();
                }
                if (n.getY() < minY) {
                    minY = n.getY();
                }
            }

            double w = ((maxX - minX));
            double h = ((maxY - minY));

            double rap = 1;
            double rh = h / w;
            double rhC = (mappa_jPanel.getSize().height * 1.0) / (mappa_jPanel.getSize().width * 1.0);
            if (rh > rhC) {
                rap = (mappa_jPanel.getSize().height * 1.0) / h;
            } else {
                rap = (mappa_jPanel.getSize().width * 1.0) / w;
            }

            double dist = Double.MAX_VALUE;

            //Stampa nodi
            for (Node n : nodes_paint.values()) {
                double x1 = (n.getX() - minX * 1.0) * rap;
                double y1 = (n.getY() - minY * 1.0) * rap;
                double d = (x - x1) * (x - x1) + (y - y1) * (y - y1);
                if (d < dist) {
                    dist = d;
                    ndOut = n;
                }

            }
        }
        return ndOut;
    }

    private boolean disegnaMap(File file) {
        if (file != null) {
            if (importPlotMap.readFile(file)) {
                nodes = importPlotMap.getNodes();
                arcs = importPlotMap.getArcs();

                //per risolvere bug --> disegna parte del grafo quando si crea la mappa importata
                nodes_paint = nodes;
                arcs_paint = arcs;

                return true;
            }
        }
        return false;
    }

    private boolean esportaMap(File file) {
        if (file != null) {
            exportMap.export(file, nodes, arcs);
            nodes = exportMap.getNodes();
            arcs = exportMap.getArcs();

            //manca controllo nodes, arcs is empty
            return true;
        }

        return false;
    }

    private void disegna(Graphics gg) {

        Graphics2D g = (Graphics2D) gg;
        g.setColor(Color.black);

        int minX = Integer.MAX_VALUE;
        int maxX = Integer.MIN_VALUE;
        int minY = Integer.MAX_VALUE;
        int maxY = Integer.MIN_VALUE;

        if (nodes_paint != null && arcs_paint != null) {
            for (Node n : nodes_paint.values()) {
                if (n.getX() > maxX) {
                    maxX = n.getX();
                }
                if (n.getX() < minX) {
                    minX = n.getX();
                }
                if (n.getY() > maxY) {
                    maxY = n.getY();
                }
                if (n.getY() < minY) {
                    minY = n.getY();
                }
            }

            double w = ((maxX - minX));
            double h = ((maxY - minY));

            double rap = 1;
            double rh = h / w;
            double rhC = (mappa_jPanel.getSize().height * 1.0) / (mappa_jPanel.getSize().width * 1.0);
            if (rh > rhC) {
                rap = (mappa_jPanel.getSize().height * 1.0) / h;
            } else {
                rap = (mappa_jPanel.getSize().width * 1.0) / w;
            }

            //Disegna archi
            for (Arc arc : arcs_paint) {

                if (arc.getMark() == 1) {
                    g.setColor(Color.blue);
                    g.setStroke(new BasicStroke(2));
                }
                if (arc.getMark() == 0) {
                    g.setColor(Color.black);
                    g.setStroke(new BasicStroke(1));

                }
                double x1 = (arc.getFrom().getX() - minX * 1.0) * rap;
                double y1 = (arc.getFrom().getY() - minY * 1.0) * rap;
                double x2 = (arc.getTo().getX() - minX * 1.0) * rap;
                double y2 = (arc.getTo().getY() - minY * 1.0) * rap;

                g.drawLine((int) x1, (int) y1, (int) x2, (int) y2);
            }

            //Disegna nodi
            for (Node n : nodes_paint.values()) {
                double x1 = (n.getX() - minX * 1.0) * rap;
                double y1 = (n.getY() - minY * 1.0) * rap;
                int mark = n.getMark();

                //studenti
                Route route = n.getRoute();
                int num_studenti = n.getNum_studenti();

                if (num_studenti > 0) {
                    g.setColor(route.getColor());
                    g.fillOval((int) x1, (int) y1, num_studenti, num_studenti);
                    g.setFont(g.getFont().deriveFont(10f));
                    g.drawString("" + n.getIndex(), (int) x1, (int) y1);
                }

                switch (mark) {
                    case -1:
                        g.setColor(Color.black);
                        break;
                    case 0:
                        g.setColor(Color.red);
                        g.setFont(g.getFont().deriveFont(10f));
                        g.drawString("" + n.getIndex(), (int) x1, (int) y1);
                        break;
                    case 1:
                        g.setColor(Color.blue);
                        g.setFont(g.getFont().deriveFont(10f));
                        g.drawString("" + n.getIndex(), (int) x1, (int) y1);
                        break;
                }
            }

            //Disegna tratte
            if (routes != null) {
                for (Iterator<Route> it = routes.iterator(); it.hasNext();) {
                    Route r = it.next();

                    g.setColor(r.getColor());

                    for (int i = 0; i < r.getNodes().size(); i++) {
                        Node r_n = r.getNodes().get(i);

                        double x = (r_n.getX() - minX * 1.0) * rap;
                        double y = (r_n.getY() - minY * 1.0) * rap;

                        g.setFont(g.getFont().deriveFont(10f));
                        g.drawString("" + r_n.getIndex(), (int) x, (int) y);

                        if (i != r.getNodes().size() - 1) {
                            Arc arc = Arc.arcByFromTo(r_n, r.getNodes().get(i + 1));

                            double x1 = (arc.getFrom().getX() - minX * 1.0) * rap;
                            double y1 = (arc.getFrom().getY() - minY * 1.0) * rap;
                            double x2 = (arc.getTo().getX() - minX * 1.0) * rap;
                            double y2 = (arc.getTo().getY() - minY * 1.0) * rap;

                            g.setStroke(new BasicStroke(2));
                            g.drawLine((int) x1, (int) y1, (int) x2, (int) y2);

                        }
                    }
                }
            }
        }
    }
}
